import { Rooster, Player, DailyQuest, Skill, Element } from './types';

export const RARITY_COLORS: Record<string, string> = {
  Common: '#9CA3AF',
  Rare: '#3B82F6',
  Epic: '#A855F7',
  Legendary: '#FFD700',
  Mythic: '#FF4444',
  Divine: '#FF69B4',
};

export const RARITY_ORDER = ['Common', 'Rare', 'Epic', 'Legendary', 'Mythic', 'Divine'];

export const ELEMENT_COLORS: Record<string, string> = {
  Fire: '#FF6B35',
  Water: '#3B82F6',
  Nature: '#22C55E',
  Lightning: '#EAB308',
  Ice: '#67E8F9',
  Shadow: '#A855F7',
  Light: '#FDE047',
  Metal: '#9CA3AF',
};

export const CLASS_ICONS: Record<string, string> = {
  Guardian: 'shield',
  Warrior: 'sword',
  Assassin: 'zap',
  Mage: 'star',
  Support: 'heart',
  Berserker: 'alert-triangle',
};

export const ELEMENT_EMOJIS: Record<string, string> = {
  Fire: '🔥',
  Water: '💧',
  Nature: '🌿',
  Lightning: '⚡',
  Ice: '❄️',
  Shadow: '🌑',
  Light: '☀️',
  Metal: '⚙️',
};

const fireSkills: Skill[] = [
  { id: 'fire_peck', name: 'Fire Peck', element: 'Fire', damage: 85, energyCost: 2, description: 'A blazing strike that burns the enemy.' },
  { id: 'flame_wing', name: 'Flame Wing', element: 'Fire', damage: 110, energyCost: 3, effect: 'Burn', description: 'Sweeping fire wing attack that applies Burn.' },
  { id: 'inferno_charge', name: 'Inferno Charge', element: 'Fire', damage: 150, energyCost: 5, description: 'Charges with full body engulfed in flames.' },
  { id: 'phoenix_dive', name: 'Phoenix Dive', element: 'Fire', damage: 200, energyCost: 7, effect: 'Revive', description: 'Legendary dive with a chance to revive if KO\'d.' },
];

const lightningSkills: Skill[] = [
  { id: 'thunder_peck', name: 'Thunder Peck', element: 'Lightning', damage: 90, energyCost: 2, description: 'A fast shocking strike.' },
  { id: 'chain_bolt', name: 'Chain Bolt', element: 'Lightning', damage: 120, energyCost: 4, effect: 'Shock', description: 'Bounces lightning between enemies.' },
  { id: 'storm_call', name: 'Storm Call', element: 'Lightning', damage: 180, energyCost: 6, description: 'Summons a mighty thunderstorm.' },
];

const shadowSkills: Skill[] = [
  { id: 'dark_slash', name: 'Dark Slash', element: 'Shadow', damage: 100, energyCost: 2, description: 'A swift shadow blade strike.' },
  { id: 'assassinate', name: 'Assassinate', element: 'Shadow', damage: 160, energyCost: 5, effect: 'BleedCrit', description: 'Guaranteed critical hit with bleed.' },
  { id: 'soul_drain', name: 'Soul Drain', element: 'Shadow', damage: 80, energyCost: 3, effect: 'Lifesteal', description: 'Drains life from the target.' },
];

const iceSkills: Skill[] = [
  { id: 'ice_peck', name: 'Ice Peck', element: 'Ice', damage: 75, energyCost: 2, effect: 'Freeze', description: 'A frigid peck that may freeze.' },
  { id: 'blizzard_wing', name: 'Blizzard Wing', element: 'Ice', damage: 130, energyCost: 4, effect: 'Freeze', description: 'Icy wing sweep with freeze chance.' },
  { id: 'glacier_smash', name: 'Glacier Smash', element: 'Ice', damage: 170, energyCost: 6, description: 'Crashes down with massive ice force.' },
];

const lightSkills: Skill[] = [
  { id: 'heal_light', name: 'Holy Heal', element: 'Light', damage: 0, energyCost: 3, effect: 'Heal', description: 'Restores HP to all allies.' },
  { id: 'sun_burst', name: 'Sun Burst', element: 'Light', damage: 140, energyCost: 5, description: 'Radiant explosion of solar energy.' },
  { id: 'holy_shield', name: 'Holy Shield', element: 'Light', damage: 0, energyCost: 4, effect: 'Shield', description: 'Grants divine protection to all allies.' },
];

const metalSkills: Skill[] = [
  { id: 'iron_peck', name: 'Iron Peck', element: 'Metal', damage: 95, energyCost: 2, description: 'A powerful iron-hard strike.' },
  { id: 'shield_bash', name: 'Shield Bash', element: 'Metal', damage: 80, energyCost: 3, effect: 'Stun', description: 'Bashes with a metal shield, may stun.' },
  { id: 'titan_stomp', name: 'Titan Stomp', element: 'Metal', damage: 190, energyCost: 7, description: 'Earth-shaking stomp of pure metal force.' },
];

export const SAMPLE_ROOSTERS: Rooster[] = [
  {
    id: 'r001',
    name: 'Ignis Prime',
    rarity: 'Divine',
    class: 'Berserker',
    element: 'Fire',
    level: 85,
    evolutionStage: 'Divine',
    stats: { hp: 4200, attack: 380, defense: 220, speed: 310, critical: 45, accuracy: 92, dodge: 28, energy: 10, luck: 35 },
    baseStats: { hp: 3000, attack: 280, defense: 160, speed: 240, critical: 35, accuracy: 85, dodge: 20, energy: 10, luck: 25 },
    skills: fireSkills,
    bodyParts: { head: 'Dragon Head', beak: 'Venom Beak', wings: 'Storm Wings', legs: 'Titan Legs', tail: 'Phoenix Tail' },
    genes: { A: { dominant: 'Fire', recessive: 'Light', hidden: 'Mythic' }, B: { dominant: 'Berserker', recessive: 'Warrior', hidden: 'Mage' }, C: { dominant: 'Divine', recessive: 'Mythic', hidden: 'Legendary' } },
    image: 'rooster_fire',
    acquiredAt: '2024-01-15',
    breedCount: 2,
  },
  {
    id: 'r002',
    name: 'Voltaris Echo',
    rarity: 'Mythic',
    class: 'Assassin',
    element: 'Lightning',
    level: 72,
    evolutionStage: 'Mythic',
    stats: { hp: 2800, attack: 420, defense: 150, speed: 480, critical: 65, accuracy: 88, dodge: 45, energy: 10, luck: 40 },
    baseStats: { hp: 2000, attack: 320, defense: 100, speed: 380, critical: 55, accuracy: 80, dodge: 38, energy: 10, luck: 30 },
    skills: lightningSkills,
    bodyParts: { head: 'Thunder Head', beak: 'Iron Beak', wings: 'Storm Wings', legs: 'Shadow Legs', tail: 'Ice Tail' },
    genes: { A: { dominant: 'Lightning', recessive: 'Fire', hidden: 'Shadow' }, B: { dominant: 'Assassin', recessive: 'Berserker', hidden: 'Warrior' }, C: { dominant: 'Mythic', recessive: 'Legendary', hidden: 'Epic' } },
    image: 'rooster_fire',
    acquiredAt: '2024-02-08',
    breedCount: 1,
  },
  {
    id: 'r003',
    name: 'Umbros Shade',
    rarity: 'Legendary',
    class: 'Assassin',
    element: 'Shadow',
    level: 60,
    evolutionStage: 'Legend',
    stats: { hp: 2400, attack: 350, defense: 130, speed: 420, critical: 55, accuracy: 85, dodge: 50, energy: 10, luck: 45 },
    baseStats: { hp: 1800, attack: 270, defense: 90, speed: 330, critical: 42, accuracy: 78, dodge: 40, energy: 10, luck: 35 },
    skills: shadowSkills,
    bodyParts: { head: 'Shadow Head', beak: 'Venom Beak', wings: 'Storm Wings', legs: 'Shadow Legs', tail: 'Phoenix Tail' },
    genes: { A: { dominant: 'Shadow', recessive: 'Lightning', hidden: 'Fire' }, B: { dominant: 'Assassin', recessive: 'Mage', hidden: 'Support' }, C: { dominant: 'Legendary', recessive: 'Epic', hidden: 'Rare' } },
    image: 'rooster_shadow',
    acquiredAt: '2024-02-20',
    breedCount: 3,
  },
  {
    id: 'r004',
    name: 'Aquara Frost',
    rarity: 'Legendary',
    class: 'Mage',
    element: 'Ice',
    level: 55,
    evolutionStage: 'Legend',
    stats: { hp: 2600, attack: 300, defense: 280, speed: 280, critical: 35, accuracy: 90, dodge: 22, energy: 10, luck: 30 },
    baseStats: { hp: 2000, attack: 230, defense: 210, speed: 210, critical: 26, accuracy: 83, dodge: 16, energy: 10, luck: 22 },
    skills: iceSkills,
    bodyParts: { head: 'Phoenix Head', beak: 'Iron Beak', wings: 'Angel Wings', legs: 'Titan Legs', tail: 'Ice Tail' },
    genes: { A: { dominant: 'Ice', recessive: 'Water', hidden: 'Light' }, B: { dominant: 'Mage', recessive: 'Support', hidden: 'Guardian' }, C: { dominant: 'Legendary', recessive: 'Epic', hidden: 'Rare' } },
    image: 'rooster_ice',
    acquiredAt: '2024-03-01',
    breedCount: 0,
  },
  {
    id: 'r005',
    name: 'Solaria Dawn',
    rarity: 'Legendary',
    class: 'Support',
    element: 'Light',
    level: 58,
    evolutionStage: 'Legend',
    stats: { hp: 3200, attack: 180, defense: 350, speed: 260, critical: 20, accuracy: 95, dodge: 30, energy: 10, luck: 55 },
    baseStats: { hp: 2400, attack: 130, defense: 270, speed: 200, critical: 14, accuracy: 88, dodge: 22, energy: 10, luck: 42 },
    skills: lightSkills,
    bodyParts: { head: 'Phoenix Head', beak: 'Iron Beak', wings: 'Angel Wings', legs: 'Titan Legs', tail: 'Phoenix Tail' },
    genes: { A: { dominant: 'Light', recessive: 'Nature', hidden: 'Fire' }, B: { dominant: 'Support', recessive: 'Mage', hidden: 'Guardian' }, C: { dominant: 'Legendary', recessive: 'Mythic', hidden: 'Epic' } },
    image: 'rooster_fire',
    acquiredAt: '2024-03-10',
    breedCount: 1,
  },
  {
    id: 'r006',
    name: 'Iron Bastion',
    rarity: 'Epic',
    class: 'Guardian',
    element: 'Metal',
    level: 42,
    evolutionStage: 'Elite',
    stats: { hp: 4800, attack: 220, defense: 480, speed: 180, critical: 15, accuracy: 80, dodge: 10, energy: 10, luck: 20 },
    baseStats: { hp: 3600, attack: 170, defense: 370, speed: 140, critical: 10, accuracy: 74, dodge: 7, energy: 10, luck: 14 },
    skills: metalSkills,
    bodyParts: { head: 'Dragon Head', beak: 'Iron Beak', wings: 'Angel Wings', legs: 'Titan Legs', tail: 'Ice Tail' },
    genes: { A: { dominant: 'Metal', recessive: 'Fire', hidden: 'Water' }, B: { dominant: 'Guardian', recessive: 'Warrior', hidden: 'Berserker' }, C: { dominant: 'Epic', recessive: 'Rare', hidden: 'Common' } },
    image: 'rooster_ice',
    acquiredAt: '2024-03-20',
    breedCount: 2,
  },
  {
    id: 'r007',
    name: 'Storm Reaper',
    rarity: 'Epic',
    class: 'Warrior',
    element: 'Lightning',
    level: 38,
    evolutionStage: 'Elite',
    stats: { hp: 2900, attack: 310, defense: 220, speed: 330, critical: 40, accuracy: 86, dodge: 32, energy: 10, luck: 28 },
    baseStats: { hp: 2200, attack: 240, defense: 170, speed: 260, critical: 30, accuracy: 79, dodge: 24, energy: 10, luck: 20 },
    skills: lightningSkills,
    bodyParts: { head: 'Thunder Head', beak: 'Iron Beak', wings: 'Storm Wings', legs: 'Titan Legs', tail: 'Phoenix Tail' },
    genes: { A: { dominant: 'Lightning', recessive: 'Metal', hidden: 'Fire' }, B: { dominant: 'Warrior', recessive: 'Berserker', hidden: 'Guardian' }, C: { dominant: 'Epic', recessive: 'Rare', hidden: 'Common' } },
    image: 'rooster_fire',
    acquiredAt: '2024-04-05',
    breedCount: 0,
  },
  {
    id: 'r008',
    name: 'Ember Wings',
    rarity: 'Rare',
    class: 'Warrior',
    element: 'Fire',
    level: 25,
    evolutionStage: 'Fighter',
    stats: { hp: 1800, attack: 240, defense: 170, speed: 250, critical: 28, accuracy: 82, dodge: 18, energy: 10, luck: 20 },
    baseStats: { hp: 1400, attack: 190, defense: 130, speed: 200, critical: 20, accuracy: 76, dodge: 13, energy: 10, luck: 14 },
    skills: [fireSkills[0], fireSkills[1]],
    bodyParts: { head: 'Dragon Head', beak: 'Iron Beak', wings: 'Storm Wings', legs: 'Titan Legs', tail: 'Ice Tail' },
    genes: { A: { dominant: 'Fire', recessive: 'Nature', hidden: 'Water' }, B: { dominant: 'Warrior', recessive: 'Berserker', hidden: 'Assassin' }, C: { dominant: 'Rare', recessive: 'Common', hidden: 'Epic' } },
    image: 'rooster_fire',
    acquiredAt: '2024-04-12',
    breedCount: 0,
  },
  {
    id: 'r009',
    name: 'Frostbite',
    rarity: 'Rare',
    class: 'Mage',
    element: 'Ice',
    level: 22,
    evolutionStage: 'Fighter',
    stats: { hp: 1600, attack: 210, defense: 190, speed: 220, critical: 25, accuracy: 84, dodge: 15, energy: 10, luck: 22 },
    baseStats: { hp: 1250, attack: 165, defense: 150, speed: 175, critical: 18, accuracy: 77, dodge: 10, energy: 10, luck: 16 },
    skills: [iceSkills[0], iceSkills[1]],
    bodyParts: { head: 'Phoenix Head', beak: 'Iron Beak', wings: 'Angel Wings', legs: 'Titan Legs', tail: 'Ice Tail' },
    genes: { A: { dominant: 'Ice', recessive: 'Water', hidden: 'Nature' }, B: { dominant: 'Mage', recessive: 'Support', hidden: 'Guardian' }, C: { dominant: 'Rare', recessive: 'Common', hidden: 'Epic' } },
    image: 'rooster_ice',
    acquiredAt: '2024-04-18',
    breedCount: 1,
  },
  {
    id: 'r010',
    name: 'Dusk Feather',
    rarity: 'Common',
    class: 'Warrior',
    element: 'Nature',
    level: 12,
    evolutionStage: 'Chick',
    stats: { hp: 1100, attack: 140, defense: 120, speed: 160, critical: 12, accuracy: 78, dodge: 10, energy: 10, luck: 12 },
    baseStats: { hp: 900, attack: 115, defense: 100, speed: 130, critical: 9, accuracy: 72, dodge: 7, energy: 10, luck: 8 },
    skills: [fireSkills[0]],
    bodyParts: { head: 'Dragon Head', beak: 'Iron Beak', wings: 'Storm Wings', legs: 'Titan Legs', tail: 'Ice Tail' },
    genes: { A: { dominant: 'Nature', recessive: 'Fire', hidden: 'Water' }, B: { dominant: 'Warrior', recessive: 'Guardian', hidden: 'Support' }, C: { dominant: 'Common', recessive: 'Rare', hidden: 'Common' } },
    image: 'rooster_fire',
    acquiredAt: '2024-05-01',
    breedCount: 0,
  },
];

export const INITIAL_PLAYER: Player = {
  username: 'GallorianKing',
  level: 42,
  exp: 7800,
  maxExp: 10000,
  gold: 124500,
  crystal: 3200,
  gems: 450,
  arenaRank: 'Diamond',
  arenaPoints: 2850,
  wins: 187,
  losses: 43,
  guildName: 'Phoenix Clan',
  guildLevel: 8,
};

export const DAILY_QUESTS: DailyQuest[] = [
  { id: 'q1', title: 'Battle 5 Times', description: 'Win any 5 battles today', progress: 3, total: 5, reward: '500 Gold', completed: false },
  { id: 'q2', title: 'Breed a Rooster', description: 'Breed 1 rooster today', progress: 1, total: 1, reward: '1 Crystal', completed: true },
  { id: 'q3', title: 'Collect Daily Bonus', description: 'Collect your daily login reward', progress: 1, total: 1, reward: '50 Gems', completed: true },
  { id: 'q4', title: 'Arena Victory', description: 'Win 2 Arena matches', progress: 0, total: 2, reward: '200 Arena Points', completed: false },
  { id: 'q5', title: 'Level Up a Rooster', description: 'Level up any rooster', progress: 0, total: 1, reward: '1000 Gold', completed: false },
];

export const ARENA_RANKS = ['Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Master', 'Grandmaster', 'Legend', 'Mythic'];
